DATA:
  DIR: /srv/datasets2/recipe1m+/food.com_data
  MAX_INGRS: 20
  MAX_INGRS_LEN: 15
  MAX_INSTRS: 20
  MAX_INSTRS_LEN: 20
  NAME: food.com
  PATH_TOKENIZED_RECIPES: /srv/datasets2/recipe1m+/food.com_data/text/tokenized_recipe.json
EVAL: {}
INFER: {}
MODEL:
  EMB_DIM: 768
  RECIPE:
    NUM_HEADS: 4
    NUM_LAYERS: 2
SAVE_PATH: models/temp.pt
TITLE:
- test
TRAIN:
  BATCH_SIZE: 8
  FINETUNE: false
  LR: 0.0001
  NUM_EPOCHS: 20
  NUM_WORKERS: 4
  SEED: 12345
  WEIGHT_DECAY: 1.0e-05
