DATA:
  DIR: /srv/datasets2/recipe1m+/food.com_data_rescaled_water
  MAX_INGRS: 20
  MAX_INGRS_LEN: 15
  MAX_INSTRS: 20
  MAX_INSTRS_LEN: 20
  NAME: food.com
  NUM_INGRS: 534
  NUM_NUTRS: 6
  NUTRS:
  - energy
  - fat
  - carb
  - protein
  - ash
  - water
  NUTR_STDS:
  - 122.5
  - 10.24
  - 17.68
  - 4.641
  - 3.38
  - 22.48
  PATH_INGRS: /srv/datasets2/recipe1m+/food.com_data_rescaled_water/nutr/simplified_food_ids_per_recipes.json
  PATH_NUTRS: /srv/datasets2/recipe1m+/food.com_data_rescaled_water/nutr/food.com_nutr_g_per_recipe.json
  PATH_TOKENIZED_RECIPES: /srv/datasets2/recipe1m+/food.com_data_rescaled_water/text/tokenized_recipe.json
EVAL: {}
IMG_MODEL_PATH: ''
INFER: {}
MODEL:
  EMB_DIM: 1024
  IMAGE:
    VISION_WIDTH: 768
  NAME: deep_nutr_vlp_direct_ingrs
  NUTR:
    HIDDEN_DIM: 2048
    NUM_LAYERS: 6
  RECIPE:
    HIDDEN_DIM: 512
    NAME: ht
    NUM_HEADS: 4
    NUM_LAYERS: 2
    PRETRAINED: google-bert/bert-base-uncased
    VOCAB_SIZE: 199438
OUT_DIR: out
RECIPE_MODEL_PATH: ''
RETRIEVAL_DIR: /tmp/food.com_net
SAVE_PATH: models/deep_nutr_vlp_water/finetune_ht
TITLE:
- test
TRAIN:
  BATCH_SIZE: 32
  FINETUNE: true
  FINETUNE_MODEL: ht
  INGRS_WEIGHT: 0.025
  LOSS: weighted_triplet
  LR: 0.0001
  MAE_WEIGHT: 0.01
  NUM_EPOCHS: 100
  NUM_WORKERS: 4
  RECIPE_LOSS_WEIGHT: 1.0
  SCALE_LR: 1.0
  SEED: 12345
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 1.0e-05
VLP_PATH: vlpcook_checkpoints/ckpt_best_eval_epoch.metric.recall_at_1_im2recipe_mean_model.pth.tar
